export const GET_TOKEN_START = 'GET_TOKEN_START';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const GET_PLANETS_START = 'GET_PLANETS_START';
export const GET_PLANETS_SUCCESS = 'GET_PLANETS';
export const GET_PLANETS_ERROR = 'GET_PLANETS_ERROR';

export const GET_VEHICLES_START = 'GET_VEHICLES_START';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES';
export const GET_VEHICLES_ERROR = 'GET_VEHICLES_ERROR';
